name: course-management
recipe: drupal10
config:
  webroot: web
  xdebug: 'develop,debug'
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        XDEBUG_MODE: debug,develop
        XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes"
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      ports:
        - "8080:80"
